### ISSUE TITLE
Mod items not showing

### ISSUE THREAD

**Issue by Legion4527** [mpbb/ironbows#10]
Hello! I have the mod installed along with some other mods and for some reason it doesn't show me the items in the mod, but it is on my mods folder. Is there any dependency for the mod?

**Comment by mpbb** [comment]
Thank you @Legion4527 for submitting an issue,

All items in the mod are craftable at the crafting table, and should also be visible in JEI or similar inventory mods. Items currently do not show up in the vanilla creative menu but this could be added. Please see the images tab on Curseforge for the crafting recipe example.

**Comment by mpbb** [comment]
This has been updated, you can now see items in JEI and the creative inventory.
