### ISSUE TITLE
client side crash with skeletal remains

### ISSUE THREAD

**Issue by DadoIrie** [mpbb/ironbows#11]
~ [ironbows](https://www.curseforge.com/minecraft/mc-mods/iron-bows-fabric)-1.4-FABRIC-1.19.2
~ [skeletalremains](https://www.curseforge.com/minecraft/mc-mods/skeletal-remains)-1.3.3-1.19.2-fabric

those 2 mods together lead to an abrupt client side crash 
`@Redirect conflict. Skipping skeletalremains.mixins.json:FOVMixin from mod skeletalremains->@Redirect::init(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z with priority 1000, already redirected by ironbows.mixins.json:FovMixin from mod ironbows->@Redirect::init(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z with priority 1000`
https://mclo.gs/8aXnijE

post a issue on both [githubs of the respective mods](https://github.com/Mlodziak00/Skeletal-Remains-Fabric/issues/6) as I don't know which mod of those 2 might be better suited to fix that as clearly both are accessing the same thing (if I got this right with my limited programming knowledge) and also to cross link those issues

**Comment by mpbb** [comment]
Thank you @dadoirie  for this issue,

It seems to me that both mods are using the default mixin priority. A possible solution would be to explicitly set the priority value. I would recommend it be changed in both mods to a unique value. I will update this today.
