### ISSUE TITLE
Damage could not be changed in the config file

### ISSUE THREAD

**Issue by FogRain25** [mpbb/ironbows#13]
Hi mpbb. I have encountered two weird problem using this mod. The durability could be changed by config normally, but the damage could be not. Every time I changed the damage and restart the game, the damage in the config file changed back to the default values.
  And by the way, the new bows could not be seen in the JEI's item list in the inventory view in survival mode. But JEI will work normally when trying to view the bows' recipes.

**Comment by mpbb** [comment]
Hi @Trevor-wen

Thank you for submitting an issue. I am aware of the JEI and creative inventory issues, these will be fixed in the next release. 

The config file issue seems more major and I will investigate and try to release a fix at the same time
