### ISSUE TITLE
(ironbows-1.20.1-FORGE-1.10) Diamond, Emerald, Netherite crossbows fire in the wrong direction

### ISSUE THREAD

**Issue by PeacemakerSofanthiel** [mpbb/ironbows#16]
I don't have any mods installed that implement wind to change the direction of arrows or anything like that. In the latest 1.20.1 version of the mod, the diamond, emerald, and netherite crossbows all fire their arrow to the right, each of them at a worse angle than the last.

**Comment by mpbb** [comment]
Thank you for submitting an issue, this will be investigated.

**Comment by mpbb** [comment]
Fixed in latest commit
